config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'welcome/index'
  root 'welcome#index'

  resources :courses do
    member do
      get 'duplicate'
      get 'available'
      get 'expired'
    end
  end

  resources :letters do
    member do
      get 'duplicate'
      get 'mail'
    end
  end

  resources :items do
    member do
      get 'expire'
    end
  end

  resources :iucat_records
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_presignin.html.erb
<div class="rvt-container rvt-container--center">
    <div class="rvt-grid rvt-p-all-md">
        <div class="rvt-grid__item-9-md-up">
             <!-- Digital Alt message -->
              <div class="rvt-alert rvt-alert--warning rvt-m-bottom-md" role="alertdialog" role="alertdialog" aria-labelledby="warning-alert-title">
                <h1 class="rvt-alert__title" id="warning-alert-title">
                  This semester, we encourage you to strongly consider identifying digital alternatives for your course reserves.
                </h1>
                <p class="rvt-alert__message ">
                  Due to their short circulation period and high demand, course reserves materials are recirculated often and without
                  quarantine. Please consider helping us to keep our IUPUI community safe.
                  Contact your <a href="https://iupui.libguides.com/librarians">subject librarian</a>
                  for more information.
                </p>
                <button type="button" class="rvt-alert__dismiss" data-alert-close>
                    <span class="v-hide">Dismiss this alert</span>
                    <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                        <path fill="currentColor" d="M9.41,8l5.29-5.29a1,1,0,0,0-1.41-1.41L8,6.59,2.71,1.29A1,1,0,0,0,1.29,2.71L6.59,8,1.29,13.29a1,1,0,1,0,1.41,1.41L8,9.41l5.29,5.29a1,1,0,0,0,1.41-1.41Z"/>
                    </svg>
                </button>
              </div>
              <!-- End Digital Alt message -->
              <div class="rvt-container">
                  <div class="rvt-grid">
                      <div class="rvt-grid__item-12-md-up">
                        <span class="rvt-ts-32 rvt-text-bold">Welcome, IUPUI instructors!</span>
                      </div>
                  </div>
              </div>
              <div class="rvt-p-left-md rvt-p-bottom-md">
              Thanks for choosing to:
              <ul>
                <li>Provide your students with hard copies of course materials for short-term checkout.</li>
                <li>Help students access required texts or items that might be hard to find.</li>
                <li>Reduce the burden of textbook costs for your students.</li>
              </ul>
              <br/>
              <%= link_to "Sign in with IU LOGIN", user_cas_omniauth_authorize_path, class: 'rvt-button', method: :post %>
          </div>
        </div>

        <div class="rvt-grid__item-3-md-up rvt-border-radius rvt-border-all rvt-p-all-sm">
              <strong>Are you a student?</strong> To see if course reserve materials are available for your class you can:
              <ul>
                <li>Check IUCAT Class Reserves to see what might be available, OR</li>
                <li>Contact the library and ask for help
                  <ul>
                    <li>University Library Service & Information desk:<br/>
                        317-274-0472<br/>
                        <a href="mailto:renewal@iupui.edu">renewal@iupui.edu</a><br/>
                    </li>
                    <li>Herron Art Library:<br/>
                        317-278-9484<br/>
                        <a href="mailto:halresrv@iupui.edu<">halresrv@iupui.edu</a><br/>
                    </li>
               </ul>
              </li>
              </ul>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <% if current_user.role?(:instructor) && !current_user.admin? %>
    <div class='rvt-p-all-sm'>
      <%= link_to "New Course", new_course_path, class: 'rvt-button' %>
    </div>
    <div class='rvt-p-all-sm'>
      <%= link_to "My Courses", courses_path, class: 'rvt-button' %>
    </div>
  <% elsif current_user.admin? %>
    <div class='rvt-p-all-sm'>
      <%= link_to "Add Course", new_course_path, class: 'rvt-button' %>
    </div>
    <div class='rvt-p-all-sm'>
      <%= link_to "List Courses", courses_path, class: 'rvt-button' %>
    </div>
    <div class='rvt-p-all-sm'>
      <%= link_to "List Items", items_path, class: 'rvt-button' %>
    </div>
    <div class='rvt-p-all-sm'>
      <%= link_to "Send Letter", letters_path, class: 'rvt-button' %>
    </div>
    <div class='rvt-p-all-sm'>
      <%= link_to "Admin", rails_admin_path, class: 'rvt-button' %>
    </div>
    <p class='rvt-text-bold'>Switch User</p>
    <%= switch_user_select style: 'width: 220px' %>
  <% else %>
    <p>Go to IUCAT to search for Course Reserve Materials.</p>
  <% end %>
<% else %>
  <%= render 'presignin' %>
<% end %>