config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'welcome/index'
  root 'welcome#index'

  resources :courses do
    member do
      get 'duplicate'
      get 'available'
      get 'expired'
    end
  end

  resources :letters do
    member do
      get 'duplicate'
      get 'mail'
    end
  end

  resources :items do
    member do
      get 'expire'
    end
  end

  resources :iucat_records
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :library, optional: true
  has_and_belongs_to_many :semesters

  def duplicate
    dup_letter = deep_clone include: :semesters
    dup_letter.sent_date = nil
    dup_letter
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy]

  include Pagy::Backend

  # GET /letters
  # GET /letters.json
  def index
    @q = Letter.ransack(params[:q])
    @pagy, @letters = pagy(policy_scope(@q.result))
  end

  # GET /letters/1
  # GET /letters/1.json
  def show
    authorize @letter
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # GET /letters/1/edit
  def edit
    authorize @letter
  end

  # GET /letters/1/duplicate
  def duplicate
    @letter = Letter.find(params[:id]).duplicate
    render action: 'new'
  end

  # GET /letters/1/mail
  def mail
    @letter = Letter.find(params[:id])
    @letter.sent_date = Time.now
    respond_to do |format|
      if @letter.save
        LetterMailer.with(letter: @letter).letter_email.deliver_later
        format.html { redirect_to @letter, notice: 'Letter was successfully sent.' }
      end
    end
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)
    @letter.recipient = helpers.recipient_list
    @letter.from = helpers.from_address
    authorize @letter
    respond_to do |format|
      if @letter.save
        format.html { redirect_to @letter, notice: 'Letter was successfully created.' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /letters/1
  # PATCH/PUT /letters/1.json
  def update
    authorize @letter
    respond_to do |format|
      if @letter.update(letter_params)
        format.html { redirect_to @letter, notice: 'Letter was successfully updated.' }
        format.json { render :show, status: :ok, location: @letter }
      else
        format.html { render :edit }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /letters/1
  # DELETE /letters/1.json
  def destroy
    authorize @letter
    @letter.destroy
    respond_to do |format|
      format.html { redirect_to letters_url, notice: 'Letter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:send_option, :recipient, :subject,
        :library_id, :message, :sent_date, :from, semester_ids: [])
    end
end

app/helpers/letters_helper.rb
module LettersHelper
  include Pagy::Frontend

  def show_semesters(let = false)
    letter = let || @letter
    letter.semesters.map { |sem| sem.semester.to_s }.join('<br/>').html_safe
  end

  def recipient_list(let = false)
    letter = let || @letter
    recipients = []
    letter.semesters.each do |semester|
      semester.courses.each do |course|
        recipients |= [course.instructor_email] if library_filter(course, letter)
      end
    end
    recipients.join('; ')
  end

  def from_address(let = false)
    letter = let || @letter
    return Library.find(letter.library_id).email if Library.exists?(id: letter.library_id)

    ''
  end

  private

  def library_filter(course, letter)
    return true if letter.library.nil? ||
                   letter.library == course.library ||
                   letter.library == Library.where(name: 'All').first

    false
  end
end

app/views/letters/_form.html.erb
<%= form_with(model: letter, local: true) do |form| %>
  <% if letter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(letter.errors.count, "error") %> prohibited this letter from being saved:</h2>

      <ul>
      <% letter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <% if @letter.persisted? %>
  <div class="field">
    <%= form.label :semester, 'Original Semester(s)' %>
    <%= form.collection_select :semester_ids, Semester.all, :id, :semester, { :selected => @letter.semester_ids }, { :disabled => true, :multiple => true, :name => 'letter[semester_ids][]' } %>
 </div>

 <div class="field">
   <%= form.label :library, 'Original Libray' %>
   <%= text_field @lettter, :library, {:value => @letter.library&.name || 'Both', :disabled => true} %>
 </div>

 <div class="field">
   <%= form.label :from, 'From: / To:' %>
   <%= form.text_field :from, id: :from %>
 </div>

  <div class="field">
    <%= form.label :recipient, 'Bcc: Recipents' %>
    <%= form.text_field :recipient, id: :recipient %>
  </div>
  <% else %>
  <div class="field">
    <%= form.label :semester %>
    <%= form.collection_select :semester_ids, Semester.all, :id, :semester, { :selected => @letter.semester_ids }, { :multiple => true, :name => 'letter[semester_ids][]' } %>
 </div>

 <div class="field">
   <%= form.label :library %>
   <%= form.collection_select :library_id, Library.all, :id, :name %>
 </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :subject %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :letter_message, class: 'tinymce' %>
  </div>

  <!--
  <div class="field">
    <%= form.label :sent_date %>
    <%= form.datetime_select :sent_date, id: :letter_sent_date %>
  </div>
  -->

  <div class="actions">
    <%= form.submit 'Save Letter', class: 'rvt-button'%>
  </div>
<% end %>

app/views/letters/edit.html.erb
<h1>Editing Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

<%= tinymce %>

app/views/letters/index.html.erb
<h1>Letters</h1>

<table>
  <thead>
    <tr>
      <th>Semesters</th>
      <th>Library</th>
      <th>Message</th>
      <th><%= sort_link(@q, :sent_date, 'Sent Date') %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @letters.each do |letter| %>
      <tr>
        <td><%= show_semesters(letter) %></td>
        <td><%= letter&.library&.name || 'Both' %></td>
        <td><%= sanitize(letter.message, tags:[]).truncate(100) %></td>
        <td><%= letter.sent_date %></td>
        <td>
          <div class='rvt-button-segmented' role='group'>
          <%= link_to 'Show', letter, class: 'rvt-button rvt-button--secondary rvt-button--small' %>
          <%= link_to 'Edit', edit_letter_path(letter), class: 'rvt-button rvt-button--secondary rvt-button--small' %>
          <%= link_to 'Destroy', letter, method: :delete, data: { confirm: 'Are you sure?'}, class: 'rvt-button rvt-button--secondary rvt-button--small'  %>
          <%= link_to 'Duplicate', duplicate_letter_path(letter), class: 'rvt-button rvt-button--secondary rvt-button--small' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Letter', new_letter_path, class: 'rvt-button' %>

<br/><br/>

<%== pagy_info(@pagy) %>
<%== render '/pagy/nav', locals: {pagy: @pagy} %>

app/views/letters/new.html.erb
<h1>New Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Back', letters_path %>

<%= tinymce %>

app/views/letters/show.html.erb
<h3>Letter #<%= @letter.id %></h3>
<table id="letter-table" class="rvt-table-stripes">
  <caption class="sr-only">Letter Information</caption>
  <tbody>
    <tr>
      <th scope="row">Semesters:</th>
      <td><%= show_semesters %></td>
    </tr>
    <tr>
      <th scope="row">Library:</th>
      <td><%= @letter.library.name %></td>
    </tr>
    <tr>
      <th scope="row">From: / To:</th>
      <td><%= @letter.from %></td>
    </tr>
    <tr>
      <th scope="row">Bcc: Recipients:</th>
      <td><%= @letter.recipient %></td>
    </tr>
    <tr>
      <th scope="row">Subject:</th>
      <td><%= @letter.subject %></td>
    </tr>
    <tr>
      <th scope="row">Message:</th>
      <td><%= @letter.message.html_safe %></td>
    </tr>
    <tr>
      <th scope="row">Date Sent:</th>
      <td><%= @letter.sent_date %></td>
    </tr>
  </tbody>
</table>

<div class="rvt-button-group rvt-p-top-md">
  <%= link_to 'Edit', edit_letter_path(@letter), class: 'rvt-button rvt-button--small'  %>
  <% if @letter.sent_date.nil? %>
    <%= link_to 'Send',
                mail_letter_path(@letter),
                data: { confirm: 'Are you sure?'},
                class: 'rvt-button rvt-button--small rvt-button--secondary' %>
  <% else %>
    <%= link_to 'Duplicate', duplicate_letter_path(@letter), class: 'rvt-button rvt-button--small rvt-button--secondary' %>
  <% end %>
  <%= link_to 'Previous Letters', letters_path, class: 'rvt-button rvt-button--small rvt-button--secondary' %>
</div>