config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'welcome/index'
  root 'welcome#index'

  resources :courses do
    member do
      get 'duplicate'
      get 'available'
      get 'expired'
    end
  end

  resources :letters do
    member do
      get 'duplicate'
      get 'mail'
    end
  end

  resources :items do
    member do
      get 'expire'
    end
  end

  resources :iucat_records
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :course
  belongs_to :item_status
  belongs_to :loan_period
  after_initialize :init

  validates :title, :author, :publication_date, presence: true
  validates_presence_of :digital_title, :digital_url, if: :digital_checked?

  validates_length_of :title, :author, :publication_date, :edition, :call_number,  maximum: 255

  def init
    self.item_status_id ||= pending_id
  end

  def self.pending
    items_with_status('Pending')
  end

  def self.ordering
    items_with_status('Ordering')
  end

  def self.processing
    items_with_status('Processing')
  end

  def self.items_with_status(status)
    where(item_status_id: status_id(status))
  end

  def self.pending_id
    status_id('Pending')
  end

  def self.status_id(status)
    ItemStatus.find_by(status: status).id
  end

  def self.last_24
    last_24 = Time.zone.now - 24 * 60 * 60
    where('created_at >= ? or updated_at >= ?', last_24, last_24)
  end

  def pending_id
    status_id('Pending')
  end

  def status_id(status)
    ItemStatus.find_by(status: status).id
  end

  def expired?
    return true if status_id('Expired') == self.item_status_id

    false
  end

  def digital_checked?
    return true if digital_option == true

    false
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include Pagy::Backend

  # GET /items
  # GET /items.json
  def index
    @q = Item.ransack(params[:q])
    @pagy, @items = pagy(policy_scope(@q.result))
  end

  # GET /items/1
  # GET /items/1.json
  def show
    authorize @item
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ItemPdf.new(@item)
        pdf.create_tag
        send_data pdf.render,
                  filename: "item_#{@item.id}",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /items/new
  def new
    pending = ItemStatus.find_by(status: 'Pending')
    @item = Item.new(item_status_id: pending.id)
  end

  # GET /items/1/edit
  def edit
    authorize @item
  end

  # GET /items/1/expire
  def expire
    @item = Item.find(params[:id])
    @course = Course.find(@item.course_id)
    authorize @item
    @item.item_status_id = ItemStatus.find_by(status: 'Expired').id
    respond_to do |format|
      if @item.save
        format.html { redirect_to course_url(@course), notice: 'Item expired.' }
      else
        format.html { redirect_to course_url(@course), notice: 'Item could not be expired.' }
      end
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    authorize @item
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    authorize @item
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(policy(@item).permitted_attributes)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  include Pagy::Frontend

  def item_badge(item)
    return 'rvt-badge--info' if item.item_status.status == 'Available'
    return 'rvt-badge--danger' if item.item_status.status == 'Expired'

    'rvt-badge--success'
  end

  def bod_display(item)
    return 'none' unless item.object.bod_format.present?

    'block'
  end

  def status_class(status)
    return 'rvt-button' if status == params[:status]

    'rvt-button rvt-button--secondary'
  end

  def iucat_link(item)
    return nil if item.iucat_id.nil?

    "https://iucat.iu.edu/catalog/#{item.iucat_id}"
  end

  def title_iucat_link(item)
    return item.title if item.iucat_id.nil?

    link_to iucat_link(item), target: '_blank' do
      "#{item.title} #{fa_icon 'external-link'}".html_safe
    end
  end

  def param_item_status
    return '' unless params.has_key?(:q) && params[:q].has_key?(:item_status_id_eq)

    params[:q][:item_status_id_eq]
  end

  def param_course_semester
    return '' unless params.has_key?(:q) && params[:q].has_key?(:course_semester_semester_eq)

    params[:q][:course_semester_semester_eq]
  end

  def param_libary
    return '' unless params.has_key?(:q) && params[:q].has_key?(:course_library_id_eq)

    params[:q][:course_library_id_eq]
  end
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rvt-container">
    <div class="rvt-grid">
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :course_id do %>
          Course
          <%= link_to @item.course, target: 'blank' do %>
            <%= fa_icon 'external-link' %>
          <% end %>
        <% end %>
        <%= form.text_field :course_id, disabled: true %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :iucat_id do %>
          IUCAT record number
          <a href="https://iucat.iu.edu/catalog/<%= item.iucat_id %>" target="_blank">
            <%= fa_icon 'external-link' %>
          </a>
        <% end %>
        <%= form.text_field :iucat_id, id: :item_iucat_id, disabled: true  %>
      </div>
    </div>
    <div class="rvt-grid">
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :title %>
        <%= form.text_field :title, id: :item_title, class: 'enterastab', maxlength: 255 %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :author %>
        <%= form.text_field :author, id: :item_author, class: 'enterastab', maxlength: 255 %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :publication_date %>
        <%= form.text_field :publication_date, id: :item_publication_date, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :edition %>
        <%= form.text_field :edition, id: :item_edition, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :call_number %>
        <%= form.text_field :call_number, id: :item_call_number, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :loan_period %>
        <%= form.collection_select :loan_period_id, LoanPeriod.all, :id, :length, {}, {class: 'enterastab'} %>
      </div>
      <div class="field rvt-grid__item-12-md-up rvt-grid__item-8-lg-up">
        <%= form.label :note %>
        <%= form.text_area :note, id: :item_note %>
      </div>
    </div>
    <div class="rvt-grid">
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :item_status %>
        <%= form.collection_select :item_status_id, ItemStatus.all, :id, :status, {}, {class: 'enterastab'} %>
      </div>
      <div class='rvt-grid__item-12 rvt-p-top-md'>
        <%= form.check_box :will_supply, id: 'item_will_supply', class: 'enterastab' %>
        <%= form.label :will_supply, "Patron will supply" %>
      </div>
      <div class='rvt-grid__item-12'>
        <%= form.check_box :purchase, id: 'item_purchase', class: 'enterastab' %>
        <%= form.label :purchase, "Please purchase" %>
      </div>
      <div class='rvt-grid__item-12'>
        <%= form.check_box :digital_option, id: 'item_digital_option', class: 'enterastab' %>
        <%= form.label :digital_option, "Digital option available" %>
      </div>
      <div class='rvt-grid__item-12'>
        <%= form.label :digital_title %>
        <%= form.text_field :digital_title, class: 'enterastab', maxlength: 100 %>
      </div>
      <div class='rvt-grid__item-12 rvt-p-bottom-md'>
        <%= form.label :digital_url %>
        <%= form.text_field :digital_url, class: 'enterastab', maxlength: 100 %>
      </div>

    </div>
  </div>
  <div class="actions">
    <%= form.submit 'Save Item', class: 'rvt-button' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<li class="rvt-p-bottom-sm">
  <span class="rvt-badge <%= item_badge(item) %>">
    <%= item.item_status.status %>
  </span>
  <% if item.iucat_id %>
    <%= link_to(iucat_link(item), target: '_blank') do %>
      <i><%= item.title.to_s %></i> <%= fa_icon 'external-link' %>
    <% end %>,
  <% else %>
    <i><%= item.title.to_s %></i>,
  <% end %>
  <%= item.author.to_s %>
  (<%= item.publication_date.to_s %>).
  <% if current_user.admin? %>
    <span>
      <%= link_to 'Show', item %>
      | <%= link_to 'Tag', item_path(item, format: :pdf), target: 'blank' %>
      | <%= link_to 'Edit', edit_item_path(item) %>
    </span>
  <% end %>
</li>

app/views/items/_item_row.html.erb
<tr>
  <td>
  <span class="rvt-badge <%= item_badge(item) %>">
    <%= item.item_status.status %>
  </span>
  </td>
  <td>
  <%= item.author.to_s %>
  (<%= item.publication_date.to_s %>).
  <i><%= item.title.to_s %></i>.
  <% if item.iucat_id %>
    <%= link_to(iucat_link(item), target: '_blank') do %>
      IUCAT <%= fa_icon 'external-link' %>
    <% end %>
  <% end %>
  </td>
  <td>
  <%= link_to 'Show', item %>
  <%= link_to 'Edit', edit_item_path %>
  </td>
</tr>

app/views/items/edit.html.erb
<h1 class="rvt-p-bottom-lg rvt-p-top-md">Editing Item #<%= @item.id %></h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', :back %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<div id="item-filters">
  <div class="rvt-box">
    <div class="rvt-box__header">
      Filters
    </div>
    <div class="rvt-box__body rvt-m-right-sm">
    <%= search_form_for @q do |f| %>
      <div class="rvt-grid">
        <div class="rvt-grid__item-md">
          <%= f.label :title_or_author_cont, 'Title | Author' %>
          <%= f.search_field :title_or_author_cont %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :course_name_cont, 'Course' %>
          <%= f.search_field :course_name_cont %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :course_library_id_eq, 'Library' %>
          <%= f.select :course_library_id_eq, options_from_collection_for_select(Library.where.not(name: 'All'), 'id', 'name', param_libary), include_blank: true %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :course_semester_semester_cont, 'Semester' %>
          <%= f.select :course_semester_semester_eq, options_from_collection_for_select(Semester.order(id: :desc), 'semester', 'semester', param_course_semester), include_blank: true %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :item_status_id_eq, 'Status' %>
          <%= f.select :item_status_id_eq, options_from_collection_for_select(ItemStatus.all, 'id', 'status', param_item_status), include_blank: true %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :digital_option, 'Digital alternative' %>
          <%= f.select :digital_option_eq, [['Yes', 1]], include_blank: true %>
        </div>
        <div class="rvt-grid__item">
          <%= f.submit "Filter", class: 'rvt-button rvt-m-top-md' %>
          <%= link_to 'Reset', items_path, class: 'rvt-button rvt-button--secondary rvt-m-top-md' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :id, 'ID') %></th>
      <th><%= sort_link(@q, :title) %></th>
      <th><%= sort_link(@q, :author) %></th>
      <th><%= sort_link(@q, :course_name, 'Course') %></th>
      <th><%= sort_link(@q, :course_library_name, 'Library') %></th>
      <th><%= sort_link(@q, :course_semester_semester, 'Semester') %></th>
      <th><%= sort_link(@q, :status) %></th>
      <th><%= sort_link(@q, :digital_option, 'Digital alternative') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= title_iucat_link(item) %></td>
        <td><%= item.author %></td>
        <td><%= link_to Course.find(item.course_id).name, course_path(item.course_id)%></td>
        <td><%= Course.find(item.course_id).library.name %></td>
        <td><%= Course.find(item.course_id).semester.semester %></td>
        <td><%= ItemStatus.find(item.item_status_id).status %></td>
        <td><%= "Yes" if item.digital_option == true %></td>
        <td>
          <div class='rvt-button-segmented' role='group'>
          <%= link_to 'Show', item, class: 'rvt-button rvt-button--secondary rvt-button--small' %>
          <%= link_to 'Edit', edit_item_path(item), class: 'rvt-button rvt-button--secondary rvt-button--small' %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?'}, class: 'rvt-button rvt-button--secondary rvt-button--small'  %>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Item', new_item_path, class: 'rvt-button' %>

<br/><br/>

<%== pagy_info(@pagy) %>
<%== render '/pagy/nav', locals: {pagy: @pagy} %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Item #<%= @item.id %></h3>
<table id="course-table" class="rvt-table-stripes">
  <caption class="sr-only">Course Information</caption>
  <tbody>
    <tr>
      <th scope="row">Title:</th>
      <td><%= @item.title %></td>
    </tr>
    <tr>
      <th scope="row">Author:</th>
      <td><%= @item.author %></td>
    </tr>
    <tr>
      <th scope="row">Publication Date:</th>
      <td><%= @item.publication_date %></td>
    </tr>
    <tr>
      <th scope="row">Status:</th>
      <td><%= ItemStatus.find(@item.item_status_id).status %></td>
    </tr>
    <tr>
      <th scope="row">Edition:</th>
      <td><%= @item.edition %></td>
    </tr>
    <tr>
      <th scope="row">Loan Period:</th>
      <td><%= LoanPeriod.find(@item.loan_period_id).length %></td>
    </tr>
    <tr>
      <th scope="row">Call Number:</th>
      <td><%= @item.call_number %></td>
    </tr>
    <tr>
      <th scope="row">Note:</th>
      <td><%= @item.note %></td>
    </tr>
    <tr>
      <th scope="row">IUCAT Record:</th>
      <td>
        <%= link_to(@item.iucat_id, iucat_link(@item), target: '_blank') if @item.iucat_id %>
      </td>
    </tr>
    <tr>
      <th scope="row">Course:</th>
      <td><%= link_to Course.find(@item.course_id).name, course_path(@item.course_id) %></td>
    </tr>
    <tr>
      <th scope="row">Patron will supply:</th>
      <td><%= "Yes" if @item.will_supply %></td>
    </tr>
    <tr>
      <th scope="row">Please purchase:</th>
      <td><%= "Yes" if @item.purchase %></td>
    </tr>
    <tr>
      <th scope="row">Digital alternative available:</th>
      <td><%= "Yes" if @item.digital_option %></td>
    </tr>
    <tr>
      <th scope="row">Digital title:</th>
      <td><%= @item.digital_title %></td>
    </tr>
    <tr>
      <th scope="row">Digital url:</th>
      <td><%= link_to(@item.digital_url, @item.digital_url) if @item.digital_url %></td>
    </tr>
  </tbody>
</table>

<% if current_user.admin? %>
<div class="rvt-button-group rvt-p-top-md">
  <%= link_to 'Edit', edit_item_path(@item), class: 'rvt-button rvt-button--small' %>
  <%= link_to 'Tag', item_path(format: :pdf), target: 'blank', class: 'rvt-button rvt-button--small rvt-button--secondary' %>
  <%= link_to 'Back', :back, class: 'rvt-button rvt-button--small rvt-button--secondary' %>
</div>
<% else %>
<div class="rvt-button-group rvt-p-top-md">
  <%= link_to 'Back', :back, class: 'rvt-button rvt-button--small' %>
</div>
<% end %>