config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  get 'welcome/index'
  root 'welcome#index'

  resources :courses do
    member do
      get 'duplicate'
      get 'available'
      get 'expired'
    end
  end

  resources :letters do
    member do
      get 'duplicate'
      get 'mail'
    end
  end

  resources :items do
    member do
      get 'expire'
    end
  end

  resources :iucat_records
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include Pagy::Backend

  # GET /courses
  # GET /courses.json
  def index
    @q = Course.ransack(params[:q])
    @pagy, @courses = pagy(policy_scope(@q.result))
  end

  # GET /courses/1
  # GET /courses/1.pdf
  def show
    authorize @course
    respond_to do |format|
      format.html
      format.pdf do
        pdf = CoursePdf.new(@course)
        pdf.create_tags
        send_data pdf.render,
                  filename: "course_#{@course.id}",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  # GET /courses/new
  def new
    @course = Course.new
    @course.items.build
    @course.instructor_username = current_user.uid
    @course.instructor_email = LdapService.fetch_info(current_user.uid)[:email]
  end

  # GET /courses/1/edit
  def edit
    @course.items.each do |item|
      item.user_id = @course.user_id
    end
    authorize @course
  end

  # GET /courses/1/duplicate
  def duplicate
    template = Course.find(params[:id])
    @course = template.duplicate # defined in Course.duplicate
    render action: 'new', notice: 'Review Course before Saving.'
  end

  # Get /course/1/available
  # Changes status to all items as available
  def available
    @course = Course.find(params[:id])
    authorize @course
    available_id = ItemStatus.find_by(status: 'Available').id
    @course.items.each do |item|
      item.item_status_id = available_id
      item.save
    end
    render :show
  end

  # Get /course/1/expired
  # Changes status of all course items to expired
  def expired
    @course = Course.find(params[:id])
    authorize @course
    expired_id = ItemStatus.find_by(status: 'Expired').id
    @course.items.each do |item|
      item.item_status_id = expired_id
      item.save
    end
    render :show
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.user_id = current_user.id
    @course.items.each do |item|
      item.user_id = current_user.id
    end
    authorize @course
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        # Make sure all items are owned by course_user after update
        @course.items.each do |item|
          item.user_id = @course.user_id
        end
        @course.save
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def course_params
    params.require(:course).permit(
      :name, :course_number, :instructor, :instructor_username,
      :instructor_email, :library_id, :semester_id, :department_id,
      :department_name,
      items_attributes: policy(:item).permitted_attributes
    )
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  include Pagy::Frontend

  def param_semester
    return '' unless params.has_key?(:q) && params[:q].has_key?(:semester_id_eq)

    params[:q][:semester_id_eq]
  end

  def param_library
    return '' unless params.has_key?(:q) && params[:q].has_key?(:library_id_eq)

    params[:q][:library_id_eq]
  end

  def digital_option_display(digital_option)
    return 'style=display:none;' unless digital_option
  end
end

app/views/courses/_add_items.html.erb
<%= form.nested_fields_for :items do |item_form| %>
<% expired = item_form.object.item_status_id == ItemStatus.find_by(status: 'Expired').id %>


<% if expired %>
  <div class='item_expired rvt-border-all rvt-border-radius rvt-m-bottom-sm rvt-p-all-md'>
    <div class="add_items rvt-container">
      <p><span class="rvt-badge rvt-badge--danger">ITEM EXPIRED</span></p>
<% else %>
  <div class='rvt-border-all rvt-border-radius rvt-m-bottom-sm rvt-p-all-md'>
    <div class="add_items rvt-container">
<% end %>

    <div class="rvt-grid iucat-data">
      <div class='rvt-grid__item-12-sm-up rvt-grid__item-3-md-up rvt-grid__item-3-lg-up rvt-p-bottom-md'>
        <a href="https://iucat.iu.edu" id="iucat_link___nested_field_for_replace_with_index__" class="rvt-button iucat-link-bttn" target="_iucat">
          Go to IUCAT <%= fa_icon 'external-link' %>
        </a>
      </div>
      <div class='rvt-grid__item-12-sm-up rvt-grid__item-7-md-up rvt-grid__item-7-lg-up rvt-p-bottom-md'>
        <%= item_form.text_field :iucat_id, placeholder: "Paste IUCAT URL.", onkeydown: "preventSubmit(event);", onkeyup: "checkIUCAT(__nested_field_for_replace_with_index__, event); return false;", class: 'iucat-record-id', disabled: expired %>
      </div>
      <div class='rvt-grid__item-12-sm-up rvt-grid__item-2-md-up rvt-grid__item-2-lg-up rvt-p-bottom-md'>
        <button id="iucat_data___nested_field_for_replace_with_index__" class="rvt-button iucat-data-bttn" onclick="fetchMetadata(__nested_field_for_replace_with_index__);return false;" disabled>Autofill</button>
        <a data-modal-trigger='modal-info-autofill' class='info-link' id='autofill-info-link'><%= fa_icon 'info-circle 2x' %></a>
      </div>
      <%= render 'autofill_modal' %>
    </div>

    <div class="rvt-grid">
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :title %> <%= fa_icon 'asterisk' %>
        <%= item_form.text_field :title, disabled: expired, class: 'enterastab item-title', maxlength: 255 %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :author %> <%= fa_icon 'asterisk' %>
        <%= item_form.text_field :author, disabled: expired, class: 'enterastab', maxlength: 255 %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :publication_date %> <%= fa_icon 'asterisk' %>
        <%= item_form.text_field :publication_date, disabled: expired, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :edition %>
        <%= item_form.text_field :edition, disabled: expired, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :call_number %>
        <%= item_form.text_field :call_number, disabled: expired, class: 'enterastab' %>
      </div>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :loan_period %>
        <%= item_form.collection_select :loan_period_id, LoanPeriod.all, :id, :length, {}, {disabled: expired, class: 'enterastab'} %>
      </div>
      <div class="field rvt-grid__item-12-md-up rvt-grid__item-8-lg-up">
        <%= item_form.label :note %>
        <%= item_form.text_area :note, disabled: expired %>
      </div>
    </div>
    <div class="rvt-grid">
      <div style="display:<%= bod_display(item_form) %>;"
           class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up"
           id="div_bod_format___nested_field_for_replace_with_index__">
        <%= item_form.label :bod_format, 'Books on Demand format' %>
        <%= item_form.text_field :bod_format, disabled: expired, class: 'enterastab' %>
      </div>
      <% if current_user.admin? %>
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= item_form.label :item_status %>
        <%= item_form.collection_select :item_status_id, ItemStatus.all, :id, :status, {}, {disabled: expired, class: 'enterastab'} %>
      </div>
      <% end %>
    </div>
    <div class="rvt-grid">
      <div id='div_supply___nested_field_for_replace_with_index__' class='rvt-grid__item-12'>
        <%= item_form.check_box :will_supply, disabled: expired, class: 'enterastab' %>
        <%= item_form.label :will_supply, "I will supply" %>
      </div>
      <div id='div_purchase___nested_field_for_replace_with_index__' class='rvt-grid__item-12'>
        <%= item_form.check_box :purchase, disabled: expired, class: 'enterastab' %>
        <%= item_form.label :purchase, "Please purchase" %>
        <a data-modal-trigger='modal-info-pleasepurchase' class='info-link' id='pleasepurchase-info-link'><%= fa_icon 'info-circle 2x' %></a>
      </div>
      <%= render 'pleasepurchase_modal' %>

      <div id='div_digitaloption___nested_field_for_replace_with_index__' class='rvt-grid__item-12'>
        <%= item_form.check_box :digital_option, disabled: expired, class: 'enterastab', onclick: 'digital_options_toggle($(this));' %>
        <%= item_form.label :digital_option, "Digital alternative available" %>
        <a data-modal-trigger='modal-info-digitaloption' class='info-link' id='digitaloption-info-link'><%= fa_icon 'info-circle 2x' %></a>
      </div>
      <%= render 'digitaloption_modal' %>

      <div id="digital_option_info___nested_field_for_replace_with_index__" <%= digital_option_display(item_form.object.digital_option) %>>
        <div id='div_digitaltitle___nested_field_for_replace_with_index__' class='rvt-grid__item-12'>
          <%= item_form.label :digital_title %>
          <%= item_form.text_field :digital_title, disabled: expired, class: 'enterastab', maxlength: 100 %>
        </div>
        <div id='div_digitaltitle___nested_field_for_replace_with_index__' class='rvt-grid__item-12'>
          <%= item_form.label :digital_url %>
          <%= item_form.text_field :digital_url, disabled: expired, class: 'enterastab', maxlength: 100 %>
        </div>
      </div>

      <div class='rvt-grid__item-12-sm-up rvt-grid__item-12-md-up rvt-grid__item-12-xxl-up  rvt-p-bottom-md rvt-p-top-lg'>
      <% if item_form.object.persisted? && !expired %>
        <%= link_to "Expire Item", expire_item_path(id: item_form.object.id), class: 'rvt-button rvt-button--danger' %>
      <% end %>
      <% if current_user.admin? %>
        <%= item_form.remove_nested_fields_link 'Remove Item x', class: 'rvt-button rvt-button--danger' %>
      <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/courses/_autofill_modal.erb
<div class="rvt-modal"
     id="modal-info-autofill"
     role="dialog"
     aria-labelledby="modal-info-autofill"
     aria-hidden="true"
     tabindex=-1>
     <div class="rvt-modal__inner">
        <header class="rvt-modal__header">
            <h1 class="rvt-modal__title" id="modal-example-title">Using IUCAT to Autofill Item</h1>
        </header>

        <div class="rvt-modal__body">
          <ol class="rvt-steps rvt-steps--vertical">
            <li class="rvt-steps__item">
              <span class="rvt-steps__item-content">
                <span class="rvt-steps__label">
                  Search for item in IUCAT
                </span>
                <span class="rvt-steps__indicator">
                  <span class="rvt-sr-only">Step</span> 1
                </span>
              </span>
            </li>
            <li class="rvt-steps__item">
              <span class="rvt-steps__item-content">
                <span class="rvt-steps__label">Copy URL of item</span>
                <span class="rvt-steps__indicator">
                  <span class="rvt-sr-only">Step</span> 2
                </span>
              </span>
            </li>
            <li class="rvt-steps__item">
              <span class="rvt-steps__item-content">
                <span class="rvt-steps__label">Paste URL into Course Reserves item</span>
                <span class="rvt-steps__indicator">
                  <span class="rvt-sr-only">Step</span> 3
                </span>
              </span>
            </li>
            <li class="rvt-steps__item">
              <span class="rvt-steps__item-content">
                <span class="rvt-steps__label">Autofill item</span>
                <span class="rvt-steps__indicator">
                  <span class="rvt-sr-only">Step</span> 4
                </span>
              </span>
            </li>
          </ol>

          <h4 class="rvt-p-top-md">1. Search for item in IUCAT</h4>
          <div class="rvt-p-left-md">
            Click on <%= image_tag('info/go_iucat.png', height: '32px') %>
            to open IUCAT <br/> in another browser tab.
          </div>

          <h4 class="rvt-p-top-md">2. Copy URL of item</h4>
          <div class="rvt-p-left-md">
            Copy the link from the Browser's URL bar.<br/>
            <%= image_tag('info/copy_url.png', height: '256px') %>
          </div>

          <h4 class="rvt-p-top-md">3. Paste URL into Course Reserves item</h4>
          <div class="rvt-p-left-md">
            Paste the copied URL into the field marked "Paste IUCAT URL."
            The Autofill button should now be enabled.
            <%= image_tag('info/paste_url.png', height: '48px') %>
          </div>

          <h4 class="rvt-p-top-md">4. Autofill item</h4>
          <div class="rvt-p-left-md">
            Click on <%= image_tag('info/autofill_button.png', height: '32px') %>. <br/>
            Available information pulled from IUCAT should now populate
            the item. Verify all fields are correct.
            Add another item or save course.
          </div>
        </div>

        <div class="rvt-modal__controls">
            <button type="button" class="rvt-button" data-modal-close="modal-info-autofill">OK</button>
        </div>
        <button type="button" class="rvt-button rvt-modal__close" data-modal-close="modal-info-autofill">
            <span class="rvt-sr-only">Close</span>
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                <path fill="currentColor" d="M9.41,8l5.29-5.29a1,1,0,0,0-1.41-1.41L8,6.59,2.71,1.29A1,1,0,0,0,1.29,2.71L6.59,8,1.29,13.29a1,1,0,1,0,1.41,1.41L8,9.41l5.29,5.29a1,1,0,0,0,1.41-1.41Z"/>
            </svg>
        </button>
    </div>
</div>

app/views/courses/_bod_modal.erb
<div class = "rvt-modal"
     id = "modal-bod"
     role = "dialog"
     aria-labelledby="modal-dialog-title"
     aria-hidden="true"
     tabindex=-1
     data-modal-dialog="true">
  <div class="rvt-modal__inner">
    <header class="rvt-modal__header">
      <h1>Books on Demand Item</h1>
    </header>
    <div class="rvt-modal__body">
      <p>
        This is a Books on Demand item.
        The library will order this book
        on your behalf. In most cases,
        the book can be ordered in
        print or electronic form.
        Please indicate which format
        you would prefer.
      </p>
    </div>
    <div class="rvt-modal__controls">
      <button class="rvt-button"
              onclick="Modal.close('modal-bod', function(){set_bod('ebook')});
                       return false;">
        eBook
      </button>
      <button class="rvt-button rvt-button--secondary"
              onclick="Modal.close('modal-bod', function(){set_bod('print')});
                       return false;">
        Print Book
      </button>
    </div>
  </div>
  <input type="hidden" id="bod_modal_index" />
</div>

app/views/courses/_digitaloption_modal.erb
<div class="rvt-modal"
     id="modal-info-digitaloption"
     role="dialog"
     aria-labelledby="modal-info-digitaloption"
     aria-hidden="true"
     tabindex=-1>
     <div class="rvt-modal__inner">
        <header class="rvt-modal__header">
            <h1 class="rvt-modal__title" id="modal-example-title">Digital alternative available</h1>
        </header>

        <div class="rvt-modal__body">
          This selection is for open access, freely-available, or IUPUI-owned
          digital materials. For all other materials please contact the
          librarian for your subject area.
        </div>

        <div class="rvt-modal__controls">
            <button type="button" class="rvt-button" data-modal-close="modal-info-digitaloption">OK</button>
        </div>
        <button type="button" class="rvt-button rvt-modal__close" data-modal-close="modal-info-digitaloption">
            <span class="rvt-sr-only">Close</span>
            <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
                <path fill="currentColor" d="M9.41,8l5.29-5.29a1,1,0,0,0-1.41-1.41L8,6.59,2.71,1.29A1,1,0,0,0,1.29,2.71L6.59,8,1.29,13.29a1,1,0,1,0,1.41,1.41L8,9.41l5.29,5.29a1,1,0,0,0,1.41-1.41Z"/>
            </svg>
        </button>
    </div>
</div>

app/views/courses/_ebook_modal.erb
<div class = "rvt-modal"
     id = "modal-ebook"
     role = "dialog"
     aria-labelledby="modal-dialog-title"
     aria-hidden="true"
     tabindex=-1
     data-modal-dialog="true">
  <div class="rvt-modal__inner">
    <header class="rvt-modal__header">
      <h1>Online Resource</h1>
    </header>
    <div class="rvt-modal__body">
      <p>
        The item you are trying
        to request is an eBook or
        online resource. These items are
        not available to be placed
        on reserve.
      </p>
    </div>
    <div class="rvt-modal__controls">
      <button class="rvt-button rvt-button--secondary" data-modal-close="modal-ebook">Close</button>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<%= form_for @course, html: {role: 'check-modified'} do |form| %>
<%#= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="rvt-container">
    <div class="rvt-grid">
      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :name do %>
            Course Name <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :name, id: :course_name, class: 'enterastab' %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :course_number do %>
          Course number <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :course_number, id: :course_course_number, class: 'enterastab', placeholder: 'example: X101, W131' %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :department_name do %>
          Department <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :department_name, class: 'enterastab', placeholder: 'Enter department...', data: {autocomplete_source: Department.order(:name).active.map(&:name)} %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :instructor do %>
          Instructor <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :instructor, id: :course_instructor, class: 'enterastab' %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :instructor_username do %>
          Instructor username <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :instructor_username, id: :course_instructor_username, class: 'enterastab' %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :instructor_email do %>
          Instructor email <%= fa_icon 'asterisk' %>
        <% end %>
        <%= form.text_field :instructor_email, id: :course_instructor_email, class: 'enterastab' %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :library %>
        <%= form.collection_select :library_id, Library.where.not(name: 'All'), :id, :name, {}, {class: 'enterastab'} %>
      </div>

      <div class="field rvt-grid__item-6-md-up rvt-grid__item-4-lg-up">
        <%= form.label :semester %>
        <%= form.collection_select :semester_id, Semester.active, :id, :semester, {}, {class: 'enterastab'} %>
      </div>

      <div class="rvt-grid__item-12 rvt-p-all-md">
        <%= fa_icon 'asterisk' %> indicates required.
      </div>
    </div>
  </div>



  <%= render 'bod_modal' %>
  <%= render 'non-iupui_modal' %>
  <%= render 'ebook_modal' %>
  <%= render 'add_items', form: form %>

  <div class='rvt-p-all-sm'>
    <%= form.add_nested_fields_link :items, 'Add item +', class: 'rvt-button' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Course', class: 'rvt-button', id: 'course_submit' %>
  </div>
<% end %>

app/views/courses/_non-iupui_modal.erb
<div class = "rvt-modal"
     id = "modal-non-iupui"
     role = "dialog"
     aria-labelledby="modal-dialog-title"
     aria-hidden="true"
     tabindex=-1
     data-modal-dialog="true">
  <div class="rvt-modal__inner">
    <header class="rvt-modal__header">
      <h1>Item Not Available</h1>
    </header>
    <div class="rvt-modal__body">
      <p>
        The item you are trying
        to request is not available
        through IUPUI University
        Library or through the Herron
        Art Library. <br/><br/>
        If you would like
        to have the item considered for
        purchase, click on <b>Please Purchase</b>.<br/>
        Otherwise, click on <b>Remove Item</b>.
      </p>
    </div>
    <div class="rvt-modal__controls">
      <button class="rvt-button"
              onclick="Modal.close('modal-non-iupui', function(){set_request(true)});
                       return false;">
        Please Purchase
      </button>
      <button class="rvt-button rvt-button--secondary"
              onclick="Modal.close('modal-non-iupui', function(){set_request(false)});
                       return false;">
        Remove Item
      </button>
    </div>
  </div>
  <input type="hidden" id="non_iupui_modal_index" />
</div>

app/views/courses/edit.html.erb
<h1 class="rvt-p-bottom-lg rvt-p-top-md">Editing Course #<%= @course.id %></h1>

<div class="rvt-button-group rvt-p-bottom-md">
  <%= link_to 'Show', @course, class: 'rvt-button rvt-button--small' %>
  <%= link_to 'Back', :back, class: 'rvt-button rvt-button--small rvt-button--secondary' %>
</div>

<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<div id="course-filters">
  <div class="rvt-box">
    <div class="rvt-box__header">
      Filters
    </div>
    <div class="rvt-box__body rvt-m-right-sm">
    <%= search_form_for @q do |f| %>
      <div class="rvt-grid">
        <div class="rvt-grid__item-md">
          <%= f.label :name_or_course_number_cont, 'Name|Number' %>
          <%= f.search_field :name_or_course_number_cont %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :department_name_cont, 'Department' %>
          <%= f.search_field :department_name_cont %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :instructor_or_instructor_username_cont, 'Instr|User' %>
          <%= f.search_field :instructor_or_instructor_username_cont %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :libary_id_eq, 'Library' %>
          <%= f.select :library_id_eq, options_from_collection_for_select(Library.where.not(name: 'All'), 'id', 'name', param_library), include_blank: true %>
        </div>
        <div class="rvt-grid__item-md">
          <%= f.label :semester_id_eq, 'Semester' %>
          <%= f.select :semester_id_eq, options_from_collection_for_select(Semester.order(id: :desc), 'id', 'semester', param_semester), include_blank: true %>
        </div>
        <div class="rvt-grid__item">
          <%= f.submit "Filter", class: "rvt-button rvt-m-top-md" %>
          <%= link_to 'Reset', courses_path, class: 'rvt-button rvt-button--secondary rvt-m-top-md' %>
        </div>
    <% end %>
    </div>
  </div>
</div>

<div class="spacer" style="padding-top:20px;"></div>

<div class="course-table">
  <table class="rvt-table-compact">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id) %></th>
        <th><%= sort_link(@q, :name) %></th>
        <th><%= sort_link(@q, :course_number, 'Number') %></th>
        <th><%= sort_link(@q, :department_name, 'Department') %></th>
        <th><%= sort_link(@q, :instructor) %></th>
        <th><%= sort_link(@q, :instructor_username, 'Username') %></th>
        <th><%= sort_link(@q, :library_name, 'Library') %></th>
        <th><%= sort_link(@q, :semester_semester, 'Semester') %></th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.id %></td>
          <td><%= course.name %></td>
          <td><%= course.course_number %></td>
          <td><%= course.department_name %></td>
          <td><%= course.instructor %></td>
          <td><%= course.instructor_username %></td>
          <td><%= course.library.name %></td>
          <td><%= course.semester.semester %></td>
          <td>
            <div class='rvt-button-segmented' role='group'>
            <%= link_to 'Show', course, class: 'rvt-button rvt-button--secondary rvt-button--small' %>
            <%= link_to 'Edit', edit_course_path(course), class: 'rvt-button rvt-button--secondary rvt-button--small' %>
            <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?'}, class: 'rvt-button rvt-button--secondary rvt-button--small' if current_user.admin?  %>
            <%= link_to 'Duplicate', duplicate_course_path(course), class: 'rvt-button rvt-button--secondary rvt-button--small' %>
            </div>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br/>

  <%= link_to 'New Course', new_course_path, class: 'rvt-button' %>

  <br/><br/>

  <%== pagy_info(@pagy) %>
  <%== render '/pagy/nav', locals: {pagy: @pagy} %>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<div class="rvt-button-group rvt-p-bottom-md">
  <%= link_to 'Back', :back, class: 'rvt-button rvt-button--small' %>
</div>

<%= render 'form', course: @course %>